trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # Change to 'windows-latest' if you prefer Windows agents

variables:
  QUESTION_START: '351'
  QUESTION_END: '462'
  GOOGLE_URL: 'https://www.google.com'
  REJECT_SELECTOR: '#W0wltc > div'
  SEARCH_BOX_SELECTOR: '#APjFqb'
  QUERY_TEMPLATE: 'examtopics az 104 question ${i}'
  ARTIFACT_STAGING_DIRECTORY: '$(Build.ArtifactStagingDirectory)'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    mkdir -p $(ARTIFACT_STAGING_DIRECTORY)/screenshots
    node index.js $(QUESTION_START) $(QUESTION_END) $(GOOGLE_URL) $(REJECT_SELECTOR) $(SEARCH_BOX_SELECTOR) "$(QUERY_TEMPLATE)"
  displayName: 'Run Puppeteer Script'

- publish: $(ARTIFACT_STAGING_DIRECTORY)
  artifact: screenshots
  displayName: 'Publish Artifacts'
